package ftp;

import org.apache.commons.net.ftp.FTP;
import org.apache.commons.net.ftp.FTPClient;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

/**
 * This class is used by Log class to generate its own usable instance of Apache's FTP client
 * Each Log generated by the logger will then upload its own log using its respective FtpClientLogger
 */
public class FtpClientLogger {
    /**
     * The log class will provide the following parameters to fire up the FTP Client:
     *
     * @param host
     * @param port
     * @param username
     * @param password
     * @param fileDirectory //This will be the absolute path of the chosen file to upload.
     */
    public FtpClientLogger(String host, int port, String username, String password, String fileDirectory, String fileName) {

        FTPClient ftpClient = new FTPClient();

        try {
            System.out.println("Connecting...");
            ftpClient.connect(host, port);
            System.out.println("Done connecting!");
            ftpClient.login(username, password);
            ftpClient.enterLocalPassiveMode();
            ftpClient.setFileType(FTP.BINARY_FILE_TYPE);
            // APPROACH #1: uploads first file using an InputStream
            File localFile = new File(fileDirectory + fileName);

            InputStream inputStream = new FileInputStream(localFile);

            System.out.println("Uploading log-->     " + fileName);
            boolean done = ftpClient.storeFile(fileName, inputStream);//variable to see if file was successfully transferred
            inputStream.close();
            if (done) {
                System.out.println(fileName + " was uploaded successfully");
            }
            else{
                System.out.println(ftpClient.getReplyCode());
            }

        } catch (IOException ex) {
            System.out.println("Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }
}
