package ftp;

import org.apache.commons.net.ftp.FTP;
import org.apache.commons.net.ftp.FTPClient;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

/**
 * This class is used by Log class to generate its own usable instance of Apache's FTP client
 * Each Log generated by the logger will then upload its own log using its respective FtpClientLogger
 */
public class FtpClientLogger extends Thread {

    FTPClient ftpClient;
    String fileDirectory;
    String fileName;
    float sleepInterval;

    final int MINUTE_MULTIPLIER = 60000;

    /**
     * Once initialized, the Logger class  will call on the run method of this thread class to begin waiting for a
     * chance to upload the current log file to server specified in config via FTP.
     * If the log file is empty, the thread will fall back asleep and wait for
     * the next chance.  If it is not empty, the thread will get the current date/time and update the name of the log
     * with this timestamp. Upload will then commence.
     *
     * The log class will provide the following parameters to fire up the FTP Client:
     *
     * @param host
     * @param port
     * @param username
     * @param password
     * @param fileDirectory
     * @param fileName
     * @param intervalInMinutes
     */
    public FtpClientLogger(String host, int port, String username, String password, String fileDirectory, String fileName, float intervalInMinutes) {

        ftpClient = new FTPClient();
        this.fileDirectory = fileDirectory;
        this.fileName = fileName;
        sleepInterval = intervalInMinutes * MINUTE_MULTIPLIER;


        try {
            System.out.println("Connecting...");
            ftpClient.connect(host, port);
            System.out.println("Done connecting!");
            ftpClient.login(username, password);
            ftpClient.enterLocalPassiveMode();
            ftpClient.setFileType(FTP.BINARY_FILE_TYPE);
        } catch (IOException ex) {
            System.out.println("Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

    /**
     * The main sleeper function. In here is logic that will not upload any empty log files, and the logic to upload
     * the current log with the proper timestamp
     */
    public void run() {
        while (true) {//Run this thread indefinitely until it is interrupted
            try {
                System.out.println("Go to Sleep...");
                this.sleep((long) sleepInterval);

                File localFile = new File(fileDirectory + fileName);

                if (localFile.length() == 0)//If file is empty, go back to sleep and do not upload
                    continue;

                InputStream inputStream = new FileInputStream(localFile);
                System.out.println("Uploading log-->     " + fileName);
                boolean done = ftpClient.storeFile(fileName, inputStream);//variable to see if file was successfully transferred
                inputStream.close();
                if (done) {
                    System.out.println(fileName + " was uploaded successfully");
                    localFile.delete();
                } else {
                    System.out.println(ftpClient.getReplyCode());
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            } catch (InterruptedException ex) {
                System.out.println("Shutting down thread");
            }
        }
    }
}

