#Logger Config file.  Each --- represents a new instance of Log to be created
---
name: "logger1"
interval: 5 # minutes
host: "localhost"
port: 22
username: "low3llg3org3"
password: "Pikmin123"
logFileDirectory: "C:\\Users\\M4600_SSD\\IdeaProjects\\rotatinglogger\\src\\test\\local_logs\\"
logFileName: "logger1.log"
level: "INFO"
---
name: "logger2"
interval: 3
host: "localhost"
port: 23
username: "goldengod"
password: "falconpunch"
logFileDirectory: "C:\\Users\\M4600_SSD\\IdeaProjects\\rotatinglogger\\src\\test\\local_logs\\"
logFileName: "logger2.log"
level: "INFO"